{
 "title": "mesures",
 "tags": [ "sma" ],
 "time": { "from": "now/d+6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "inverter",
    "label": "Onduleur",
    "query": {
     "query": "label_values(sunspec_01_DC_Current_DCA_A{}, ip)"
    }
   },
   { "name": "panel_wc", "query": "435" },
   { "name": "panel_nb_haut", "query": "8" },
   { "name": "panel_nb_bas", "query": "8" }
  ]
 },
 "panels": [
  {
   "title": "production du jour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time( sum( increase( sunspec_ActWh_ActWh_Wh{ip=\"$inverter\"} [1d] offset -1d ) ) [1d:1d] )",
     "legendFormat": "production totale"
    }
   ]
  },
  {
   "title": "puissance instantanée",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_Watts_W_W{ip=\"$inverter\"} )",
     "legendFormat": "sortie"
    },
    {
     "expr": "avg( sunspec_01_DC_Power_DCW_W{ip=\"$inverter\"}+sunspec_02_DC_Power_DCW_W{ip=\"$inverter\"} )",
     "legendFormat": "entrée"
    },
    {
     "expr": "avg( (sunspec_01_DC_Power_DCW_W{ip=\"$inverter\"}+sunspec_02_DC_Power_DCW_W{ip=\"$inverter\"})-sunspec_Watts_W_W{ip=\"$inverter\"} )",
     "legendFormat": "conso onduleur"
    }
   ]
  },
  {
   "title": "production derniers jours",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "last_over_time( sum( increase( sunspec_ActWh_ActWh_Wh{ip=\"$inverter\"} [1d] offset -1d ) ) [1d:1d] )",
     "legendFormat": "production totale"
    }
   ]
  },
  {
   "title": "production totale (cumul depuis le 01/04/2024)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_ActWh_ActWh_Wh{ip=\"$inverter\"} )",
     "legendFormat": "production totale"
    }
   ]
  },
  { "title": "ENTREES A et B", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "courant en entrée instantané",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_01_DC_Current_DCA_A{ip=\"$inverter\"} )",
     "legendFormat": "entrée A (haut)"
    },
    {
     "expr": "avg( sunspec_02_DC_Current_DCA_A{ip=\"$inverter\"}) ",
     "legendFormat": "entrée B (bas)"
    }
   ]
  },
  {
   "title": "courant d'entrée",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg( sunspec_01_DC_Current_DCA_A{ip=\"$inverter\"} )",
     "legendFormat": "entrée A (haut)"
    },
    {
     "expr": "avg( sunspec_02_DC_Current_DCA_A{ip=\"$inverter\"} )",
     "legendFormat": "entrée B (bas)"
    }
   ]
  },
  {
   "title": "tension en entrée instantanée",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_01_DC_Voltage_DCV_V{ip=\"$inverter\"} )",
     "legendFormat": "entrée A (haut)"
    },
    {
     "expr": "avg( sunspec_02_DC_Voltage_DCV_V{ip=\"$inverter\"} )",
     "legendFormat": "entrée B (bas)"
    }
   ]
  },
  {
   "title": "tension en entrée",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg( sunspec_01_DC_Voltage_DCV_V{ip=\"$inverter\"} )",
     "legendFormat": "entrée A (haut)"
    },
    {
     "expr": "avg( sunspec_02_DC_Voltage_DCV_V{ip=\"$inverter\"} )",
     "legendFormat": "entrée B (bas)"
    }
   ]
  },
  {
   "title": "puissance en entrée instantanée",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_01_DC_Power_DCW_W{ip=\"$inverter\"} )",
     "legendFormat": "entrée A (haut)"
    },
    {
     "expr": "avg( sunspec_02_DC_Power_DCW_W{ip=\"$inverter\"} )",
     "legendFormat": "entrée B (bas)"
    }
   ]
  },
  {
   "title": "puissance en entrée",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg( sunspec_01_DC_Power_DCW_W{ip=\"$inverter\"} )",
     "legendFormat": "entrée A (haut)"
    },
    {
     "expr": "avg( sunspec_02_DC_Power_DCW_W{ip=\"$inverter\"} )",
     "legendFormat": "entrée B (bas)"
    }
   ]
  },
  { "title": "SORTIE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "courant de sortie instantané",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_Amps_A_A{ip=\"$inverter\"} )",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "courant de sortie",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg( sunspec_Amps_A_A{ip=\"$inverter\"} )",
     "legendFormat": "courant de sortie"
    },
    { "expr": "15", "legendFormat": "limite erdf" }
   ]
  },
  {
   "title": "tension du secteur instantanée",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_Phase_Voltage_AN_PhVphA_V{ip=\"$inverter\"} )",
     "legendFormat": "tension secteur"
    }
   ]
  },
  {
   "title": "tension du secteur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg( sunspec_Phase_Voltage_AN_PhVphA_V{ip=\"$inverter\"} )",
     "legendFormat": "tension secteur"
    },
    { "expr": "220", "legendFormat": "min" },
    { "expr": "250", "legendFormat": "max" }
   ]
  },
  {
   "title": "puissance de sortie instantané",
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_Watts_W_W{ip=\"$inverter\"} )",
     "legendFormat": "puissance réelle"
    }
   ]
  },
  {
   "title": "puissance de sortie",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg( sunspec_Watts_W_W{ip=\"$inverter\"} )",
     "legendFormat": "puissance en sortie"
    },
    { "expr": "3000", "legendFormat": "limite erdf" },
    { "expr": "4000", "legendFormat": "limite onduleur" }
   ]
  },
  {
   "title": "puissance de sortie",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 54 },
   "targets": [
    {
     "expr": "avg( sunspec_Watts_W_W{ip=\"$inverter\"} )",
     "legendFormat": "puissance en sortie"
    }
   ]
  },
  {
   "title": "frequence du secteur instantané",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_Hz_Hz_Hz{ip=\"$inverter\"} )",
     "legendFormat": "frequence"
    }
   ]
  },
  {
   "title": "frequence du secteur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg( sunspec_Hz_Hz_Hz{ip=\"$inverter\"} )",
     "legendFormat": "frequence"
    }
   ]
  },
  { "title": "SYSTEME", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg( sunspec_Cabinet_Temperature_TmpCab_C{ip=\"$inverter\"} )",
     "legendFormat": "temperature"
    },
    { "expr": "60", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "resistance d'isolement PV",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "expr": "avg( sunspec_Ris_Ris_ohms{ip=\"$inverter\"} )",
     "legendFormat": "resistance d'isolement PV"
    }
   ]
  },
  {
   "title": "facteur de forme",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg( sunspec_PF_PF_Pct{ip=\"$inverter\"} )",
     "legendFormat": "facteur de forme"
    }
   ]
  },
  {
   "title": "rendement onduleur instantané",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( sunspec_Watts_W_W{ip=\"$inverter\"}/(sunspec_01_DC_Power_DCW_W{ip=\"$inverter\"}+sunspec_02_DC_Power_DCW_W{ip=\"$inverter\"}) )",
     "legendFormat": "rendement instantané"
    }
   ]
  },
  {
   "title": "rendement onduleur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg( sunspec_Watts_W_W{ip=\"$inverter\"}/(sunspec_01_DC_Power_DCW_W{ip=\"$inverter\"}+sunspec_02_DC_Power_DCW_W{ip=\"$inverter\"}) )",
     "legendFormat": "rendement"
    },
    { "expr": "0.8", "legendFormat": "__auto" }
   ]
  }
 ]
}