# my global config
global:
  scrape_interval:     10s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:

  - job_name: sma_inverter
    static_configs:
      - targets: ['IP_ADDRESS_OF_SUNSPEC_EXPORTER:9807']
